[build]
  functions = "functions"

[[redirects]]
  to = "/.netlify/functions/sendgrid"
  from = "/api/sendgrid"
  status = 200

  [redirects.headers]
     Access-Control-Allow-Origin = "*"


[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"